--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kayagi/Pictures/__hatsune_miku_vocaloid_drawn_by_mimengfeixue__e840b258465a304003ad04bb7fbf5663.png"

-- Special
background="#000205"
foreground="#bfbfc0"
cursor="#bfbfc0"

-- Colors
color0="#000205"
color1="#425e53"
color2="#155568"
color3="#3b5669"
color4="#206c79"
color5="#477b7e"
color6="#489097"
color7="#7f8082"
color8="#3f4143"
color9="#597E6F"
color10="#1C728B"
color11="#4F738C"
color12="#2B90A2"
color13="#5FA4A8"
color14="#60C0CA"
color15="#bfbfc0"
